server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    me.shawnrc.quip: INFO

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/Quip
  user: quip
  properties:
    serverTimezone: UTC
    nullNamePatternMatchesAll: true
    useSSL: false
