server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    me.shawnrc.quip: INFO

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem;MODE=MySQL
  user: sa
  properties:
    serverTimezone: UTC
    nullNamePatternMatchesAll: true
    useSSL: false
