CREATE TABLE user (
  id         INT UNSIGNED        NOT NULL AUTO_INCREMENT PRIMARY KEY,
  foreignUid VARCHAR(255)
             CHARACTER SET ascii
             COLLATE ascii_bin   NOT NULL
)
  ROW_FORMAT = COMPRESSED
  KEY_BLOCK_SIZE = 8;
